echo "===================================="
echo "        KS Discord Bot Setup        "
echo "===================================="
echo ""

# Ask for token
read -p "Enter your Discord Bot Token: " TOKEN

# Create index.js
cat > index.js <<EOF
// index.js — generated by KS setup script

const { Client, GatewayIntentBits } = require('discord.js');

const TOKEN = '$TOKEN';

const CLIENT_ID = '1315669854338154590';
const TEST_GUILD_ID = '1479445863032946800';

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds
  ],
});

client.once('ready', () => {
  console.log('╔════════════════════════════════════════════╗');
  console.log(\`║  Logged in as → \${client.user.tag}\`);
  console.log(\`║  Servers → \${client.guilds.cache.size}\`);
  console.log('╚════════════════════════════════════════════╝');
  console.log('Bot is online! Try /ping or /hello');
});

client.on('interactionCreate', async (interaction) => {
  if (!interaction.isChatInputCommand()) return;

  try {

    if (interaction.commandName === 'ping') {
      await interaction.reply('🏓 Pong!');
    }

    if (interaction.commandName === 'hello') {
      await interaction.reply(\`👋 Hello \${interaction.user.username}!\`);
    }

  } catch (err) {
    console.error('Command error:', err);

    if (!interaction.replied) {
      await interaction.reply({
        content: '⚠️ Something went wrong.',
        ephemeral: true
      }).catch(()=>{});
    }

  }
});

client.login(TOKEN)
.then(() => {
  console.log("✅ Login successful");
})
.catch((err) => {
  console.error("❌ Login FAILED — Invalid Token");
  console.error(err.message);
});

process.on('unhandledRejection', (reason) => {
  console.error('Unhandled error:', reason);
});
EOF

echo ""
echo "===================================="
echo "✅ Setup Complete!"
echo "===================================="
echo ""
echo "Run your bot with:"
echo ""
echo "node index.js"
echo ""
